import random
from colorama import Fore
import time
print("welcom!")
time.sleep(1)
print(Fore.BLUE,"%%%%%%%%%%%%%%%%%%%%%%%%%")
time.sleep(0.5)
print(Fore.RED,"#%%%%%%%%%%%%%%%%%%%%%%%#")
time.sleep(0.5)
print(Fore.RED,"#%%%%%%%%%%%%%%%%%%%%%%%#")
time.sleep(0.5)
print(Fore.BLUE,"# CYBER BUY RUBIKA-HACK!#")
time.sleep(0.5)
print(Fore.RED,"#%%%%%%%%%%%%%%%%%%%%%%%#")
time.sleep(0.5)
print(Fore.RED,"#%%%%%%%%%%%%%%%%%%%%%%%#")
time.sleep(0.5)
print(Fore.BLUE,"%%%%%%%%%%%%%%%%%%%%%%%%%")
time.sleep(0.5)
print(Fore.RED,"")
number = input("TATGET NUMBER?")
print(Fore.BLUE,"hacking...20%")
time.sleep(1.0)
print(Fore.RED,"hacking.....58%")
time.sleep(2.0)
print(Fore.BLUE,"hacking.......100%")
time.sleep(3.5)
print(Fore.RED,"",number, "hacked")
list = ['1','2','3','4','5','6','7','8','9']
a1 = random.choice(list)
a2 = random.choice(list)
a3 = random.choice(list)
a4 = random.choice(list)
a5 = random.choice(list)
print(Fore.BLUE,"","code: a1+a2+a3+a4+a5+a6")
